// Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

// Mod
archives_base_name=GravitationalModulatingAdditionalUnit
maven_group=gisellevonbingen.gmut
mod_id=gmut
mod_version=6.1
mod_name=Gravitational Modulating Additional Unit
mod_description=
mod_license=MIT
mod_homepage=https://www.curseforge.com/minecraft/mc-mods/gravitational-modulating-additional-unit
mod_source=https://github.com/gisellevonbingen/Minecraft-GravitationalModulatingAdditionalUnit
mod_issues=https://github.com/gisellevonbingen/Minecraft-GravitationalModulatingAdditionalUnit/issues

// Minecraft, Mod Loader
mc_version=1.21.1
neoforge_loader_version=4
neoforge_api_version=21.1.133
neoforge_api_version_range=[21.1.133,)
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
neogradle.subsystems.conventions.sourcesets.enabled=false

// Implementation
mekanism_version=10.7.11.76
mekanism_version_range=[10.7.11,)

// Runtime Only
jei_version=19.21.0.247
